# Site setings
name: 'Stephan Osterburg'
description: 'Supervisor/Technical Lead - Machine Learning Engineer'
meta_description:
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "A computer graphics, visual effects, and animation expert with a background in architecture and a keen interest in machine learning."
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://stephanosterburg.github.io/

# Add your GA Tracking Id
ga_analytics:

# Contact form setings
email: stephanosterburg@gmail.com
# contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'sosterburg'
medium: '@sosterburg'
linkedin: 'stephanosterburg'
github: 'osterburg'
stackoverflow: 'osterburg'
codepen:

# Navigation
navigation:
  - text: HOME
    url: /
  - text: ABOUT
    url: /about
  - text: PORTFOLIO
    url: /portfolio
  - text: SCRAPBOOK
    url: https://app.gitbook.com/@osterburg/s/scrapbook/
  - text: CONTACT ME
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

timezone: US/Pacific

# Other
markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: compressed  # You might prefer to minify using :compressed :expanded

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - LICENSE.txt
  - README
  - README.md
  - Rakefile
  - config
  - changelog.md
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
