openapi: 3.0.0
info:
  title: News Content
  version: '0.1'
  description: >-
    API that accepts a text string and returns its accuracy of reliablility in
    percent (%).
  contact:
    email: stephanosterburg@gmail.com
    name: Stephan Osterburg
    url: 'https://stephanosterburg.github.io'
  license:
    name: MIT
    url: 'https://choosealicense.com/licenses/mit/'
paths:
  /calc_reliablity:
    post:
      description: Calculate reliablity accuracy
      requestBody:
        description: Json with single field containing text to predict reliability
        required: true
        content:
          application/json: {}
      responses:
        '200':
          description: Returns accuracy of reliablility in the provided text in percent (%)
          content:
            application/json: {}
